name: qruto_budget
description: A Budget app.
version: 4.6.1+16
publish_to: none


environment:
  sdk: ^3.1.0
  flutter: ">=3.1.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  bloc: ^9.0.0
  rxdart: ^0.28.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  formz: ^0.8.0
  google_fonts: ^6.3.2
  meta: ^1.7.0
  http: ^1.1.0
  chart:
    path: packages/chart
  form_inputs:
    path: packages/form_inputs
  bloc_concurrency: ^0.3.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.5.0
  flutter_native_splash: ^2.4.5
  go_router: ^14.8.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.0.8
  animations: ^2.0.11
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  in_app_update: ^4.2.3
  flutter_screenutil: ^5.9.3
  google_sign_in: ^6.2.1
  googleapis: ^14.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  awesome_snackbar_content: ^0.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  drift_dev: ^2.29.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
          weight: 900
