name: cache_client
description: A cache client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

